### ISSUE TITLE
Role doesn't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-elasticsearch-curator#11]
See: https://github.com/elastic/curator/issues/1496

Basically, on Ubuntu 20.04, you get the following error:

```
Collecting elasticsearch-curator
  Downloading https://files.pythonhosted.org/packages/34/78/787a52834656f7f5dab6d709e38876c4d2604f0e1a16d17937d00330b0c5/elasticsearch-curator-5.8.1.tar.gz (225kB)
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
      Failed building wheel for pyyaml
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File \"/tmp/pip-install-56eg3knu/elasticsearch-curator/setup.py\", line 39, in <module>
        from cx_Freeze import setup, Executable
    ModuleNotFoundError: No module named 'cx_Freeze'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File \"/usr/lib/python3/dist-packages/setuptools/installer.py\", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File \"/usr/lib/python3.8/subprocess.py\", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpi6s1y7mu', '--quiet', 'pyyaml==3.13']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File \"<string>\", line 1, in <module>
      File \"/tmp/pip-install-56eg3knu/elasticsearch-curator/setup.py\", line 144, in <module>
        setup(
      File \"/usr/lib/python3/dist-packages/setuptools/__init__.py\", line 143, in setup
        _install_setup_requires(attrs)
      File \"/usr/lib/python3/dist-packages/setuptools/__init__.py\", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 1066, in best_match
        return self.obtain(req, installer)
      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 1078, in obtain
        return installer(requirement)
      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File \"/usr/lib/python3/dist-packages/setuptools/installer.py\", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpi6s1y7mu', '--quiet', 'pyyaml==3.13']' returned non-zero exit status 1.
    
    ----------------------------------------
```

**Comment by geerlingguy** [comment]
The fix (it seems) is to install `python3-wheel`.

**Comment by gardart** [comment]
Thank you so much for your great work. I was testing ELK setup from your Ansible Book but got this when running the role for curator. Below are the errors when I run this manually inside the vm.

```
vagrant@logs:~$ pip3 install elasticsearch-curator
Collecting elasticsearch-curator
  Downloading elasticsearch-curator-5.8.1.tar.gz (225 kB)
     |████████████████████████████████| 225 kB 750 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-59e7huye/elasticsearch-curator/setup.py'"'"'; __file__='"'"'/tmp/pip-install-59e7huye/elasticsearch-curator/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-59e7huye/elasticsearch-curator/pip-egg-info
         cwd: /tmp/pip-install-59e7huye/elasticsearch-curator/
    Complete output (20 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-59e7huye/elasticsearch-curator/setup.py", line 39, in <module>
        from cx_Freeze import setup, Executable
    ModuleNotFoundError: No module named 'cx_Freeze'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-59e7huye/elasticsearch-curator/setup.py", line 144, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (urllib3 1.24.3 (/tmp/pip-install-59e7huye/elasticsearch-curator/.eggs/urllib3-1.24.3-py3.8.egg), Requirement.parse('urllib3<1.26,>=1.25.4'), {'botocore'})
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by gardart** [comment]
This seems to fix the issue, at least for now

```
pip install "boto3<1.16" "botocore<1.19"
```

**Comment by geerlingguy** [comment]
@gardart - Yeah, waiting on curator to release a new update... :(

**Comment by edgester** [comment]
@gardart - Have you tried "pip3 install git+https://github.com/elastic/curator.git@99bb6d46823ac33fed399f5b0786e33dee2e9058"? That should install a working version of the curator module from git.
